Algoritmo "CalculosOperacaoBasica"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
resp1, resp2, resp3, resp4, resp5, resp6, resp7 : real
nome: caracter
Inicio
resp1 <- 2 * 6 /3

resp2 <- 3 + 2 * 4

resp3 <- (3+2)*4

resp4 <- 2*3^4

resp5 <-60/(3+2)*4

resp6 <-60/((3+2)*4)

resp7 <-10+20/4-2*3

escreval("2 * 6 / 3 = ", resp1)
escreval("3 + 2 * 4 = ", resp2)
escreval ("(3+2)*4)= ", resp3)
escreval ("2*3^4)=" , resp4)
escreval ("60/(3+2)*4=", resp5)
escreval ("60/((3+2)*4)=", resp6)
escreval ("10+20/4-2*3=", resp7)
Fimalgoritmo