Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/09/2026
Var
// Seção de Declarações das variáveis 
 x: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 x <- -1

   enquanto x < 10 faca
      se x > 5 entao
         escreva(x)
      senao
         escreval("")
      fimse

      se x = 4 entao
         interrompa
      fimse

      x <- x + 2
   fimenquanto

Fimalgoritmo