Algoritmo "calculadorademedia"

Var
// Seção de Declarações das variáveis
nome: caractere
nota1, nota2, media: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("digite o nome do aluno: ")
leia (nome)
escreval ("digite a primeira nota: ")
leia (nota1)
escreval    ("digite a segunda nota")
leia (nota2)


//caluculo de processamento de dados

media <- (nota1+nota2)/2
escreval ("aluno: ", nome)
escreval ("media final: ", media)

Fimalgoritmo