Algoritmo "IMPAPA"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
   // Seção de Declarações das variáveis
   X, SOMA : INTEIRO

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   ESCREVA ("DIGITE UM NUMERO INTEIRO: ")
   LEIA (X)
   ENQUANTO X<>0 FACA
      SE X % 2 <> 0 ENTAO
         X <- X+1
      FIMSE

      SOMA <- 5 * X + 20
      ESCREVAL ("SOMA=: ")
      ESCREVA ("DIGITE UM NUMERO INTEIRO: ")
      LEIA (x)
   FIMENQUANTO


Fimalgoritmo