Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/09/2026
Var
// Seção de Declarações das variáveis 
 x: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  RESP <- "sim"

   enquanto (RESP <> "NAO") faca
      escreva("Digite um numero: ")
      leia(x)

      R <- x * 3

      escreva(R)

      escreva("Deseja continuar? SIM/NAO")
      leia(RESP)
   fimenquanto


Fimalgoritmo