Algoritmo "Rotina do Allan Douglas"


Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 EScreval ("Primeiro despertador começa as 3:30")
 escreval ("segundo despertador começa as 3:40")
 escreval (" devo levantar as 3:50 para não atrazar no trabalho")
 escreval ("Me arrumo para trabalhar de motorista e saio as 4:00")
 escreval ("as 4:15 chego no trabalho e encotro 15 min para o dejejum")
 escreval ("começa a rota as 4:30 buscar mercadorias na manaus moderna")
 escreval ("11:30 o trabalho termina e começo a me dirigir para casa")
 escreval ("chego em casa 12:00, nesse horário tomo banho e almoço")
 escreval ("12:30 saio de casa para o curso")
 escreval ("começa o curso")
 escreva (" as 15:30 é o horário de intervalo")
 escreval ("as 17:30 o curso termina e ja inicio a volta pra casa")
 escreval ("17:30 chego em casa e me preparo para ir a biblioteca de estudos")
 escreval ("chego a biblioteca de estudos as 18:00")
 escreval ("termino os estudos as 20:30 e me dirijo para merendar na rua")
 escreval ("as 22:00 chego em casa e me preparo para ir dormir")
 escreval ("Rotina finalizada para um novo ciclo no dia seguinte")
 escreval (" A rotina não é absoluta por causa da variavel humana")
 escreval ("Fim")

Fimalgoritmo