Algoritmo "validar senha"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2026
Var
// Seção de Declarações das variáveis 
   senha: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
        repita
        escreval ("DIGITE A SENHA (1234): ")
        LEIA (SENHA)
        ATE SENHA = 1234
        ESCREVAL ("SENHA CORRETA, ACESSO LIBERADO!")

Fimalgoritmo